---
name: Build and Push Autogen Studio Image

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/autogenstudio/**/*.json'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
      - name: Login to Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pre-build autogen studio image
        uses: devcontainers/ci@a56d055efecd725e8cfe370543b6071b79989cc8
        with:
          subFolder: src/autogenstudio
          imageName: docker.io/robinmordasiewicz/autogenstudio
          cacheFrom: docker.io/robinmordasiewicz/autogenstudio
          push: always
